version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
